name: Actualización automática de precios

on:
  schedule:
    - cron: '0 8 * * *'  # Cada día a las 08:00 UTC (10:00 hora española)
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  actualizar-precios:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: pip install requests beautifulsoup4

    - name: Ejecutar scraper
      run: python scripts/scraper.py

    - name: Confirmar y subir cambios
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add precios_diarios.json
        git commit -m "Actualización automática de precios - $(date +'%Y-%m-%d')" || echo "No hay cambios"
        git push


